export const Vietnamese = {

  // resource
  img_nothing_to_show: 'https://i.pinimg.com/originals/0c/45/0c/0c450c5a9349bb992220b33ee7a0f41a.gif',

  // language
  home: 'Trang chủ',
  category: 'Danh mục',
  product: 'Sản phẩm',
  customer: 'Khách hàng',
  order: 'Đơn hàng',
  collection: 'Bộ sưu tập',
  coupon: 'Mã giảm giá',
  logout: 'Đăng xuất',
  login: 'Đăng nhập',
  detail_product: 'Chi tiết sản phẩm',
  detail_order: 'Chi tiết đơn hàng',
  detail_customer: 'Chi tiết khách hàng',
  create_collection: 'Thêm sưu tập',
  detail_collection: 'Chi tiết sưu tập',
  create_product: 'Thêm sản phẩm',

  // attribute
  id: 'ID',
  name: 'Tên',
  type: 'Loại',
  size: 'Kích thước',
  table_size: 'Bảng kích cỡ',
  quantity: 'Số lượng',
  image: 'Hình ảnh',
  preview: 'Xem trước',
  review: 'Đánh giá',
  product_quality: 'Chất lượng sản phẩm',
  your_review: 'Đánh giá của bạn',
  description: 'Mô tả',
  product_description: 'Mô tả sản phẩm',
  excerpt: 'Mô tả ngắn',
  price: 'Giá bán',
  weight: 'Trọng lượng',
  material: 'Chất liệu',
  original_price: 'Giá gốc',
  on_sale: 'Đang giảm giá',
  min_qty: 'Số lượng tối thiểu',
  max_qty: 'Số lượng tối đa',
  variants: 'Biến thể',
  variant: 'Biến thể',
  color: 'Màu sắc',
  variant_name: 'Tên biến thể',
  variant_value: 'Giá trị biến thể',
  is_active: 'Tình trạng',
  used: 'Đã dùng',
  all: 'Tổng',
  rating: 'Đánh giá',
  discount: 'Giảm giá',
  valid_from: 'Từ ngày',
  valid_to: 'Đến ngày',
  product_is_on_sale: 'Sản phẩm đang giảm giá',
  product_is_in_stock: 'Sản phẩm được mở bán',
  membership: ' Điểm thành viên',
  min_order: 'Đơn hàng tối thiểu',
  max_discount: 'Giảm tối đa',
  percentage: 'Phần trăm',
  list_coupon: 'Danh sách mã giảm giá',
  order_date: 'Ngày đặt hàng',
  order_id: 'Mã đơn hàng',
  customer_id: 'Mã khách hàng',
  total: 'Tổng tiền',
  detail: 'Chi tiết',
  payment_method: 'Phương thức thanh toán',
  status: 'Trạng thái',
  product_id: 'Mã sản phẩm',
  sub_total: 'Tạm tính',
  order_value: 'Giá trị đơn hàng',
  delivery_fee: 'Phí vận chuyển',
  ordered: 'Đã đặt',
  delivered: 'Đã giao',
  cancelled: 'Đã hủy',
  processing: 'Đang xử lý',
  completed: 'Đã hoàn thành',
  created_date: 'Ngày tạo',
  gender: 'Giới tính',
  male: 'Nam',
  female: 'Nữ',
  undefined: 'Không xác định',
  dob: 'Ngày sinh',
  order_history: 'Lịch sử đơn hàng',

  // button
  add_category: 'Thêm danh mục',
  update_category: 'Cập nhật danh mục',
  modify: 'Sửa',
  delete: 'Xóa',
  add: "Thêm",
  close: 'Đóng',
  cancel: 'Hủy',
  filter: 'Lọc',
  add_product: 'Thêm sản phẩm',
  update_product: 'Cập nhật sản phẩm',
  add_coupon: 'Thêm mã giảm giá',
  update_coupon: 'Cập nhật mã giảm giá',
  update_status: 'Cập nhật trạng thái',
  change: 'Thay đổi',
  refresh: 'Làm mới',
  add_image: 'Thêm hình ảnh',
  submit_your_review: 'Gửi đánh giá của bạn',

  // confirmation
  confirm_add_product: 'Bạn có chắc chắn muốn thêm sản phẩm này không?',
  confirm_add_coupon: 'Bạn có chắc chắn muốn thêm mã giảm giá này không?',
  confirm_update_coupon: 'Bạn có chắc chắn muốn cập nhật mã giảm giá này không?',
  confirm_delete: 'Bạn có chắc chắn muốn xóa không?',
  confirm_add: 'Bạn có chắc chắn muốn thêm không?',
  confirm_update: 'Bạn có chắc chắn muốn cập nhật không?',
  error_update_status: 'Bạn không thể cập nhật trạng thái đơn hàng này',
  confirm_logout: 'Bạn có chắc chắn muốn đăng xuất không?',

  // message
  require_fill_all: 'Vui lòng nhập đầy đủ thông tin',
  require_fill_image: 'Vui lòng tải ảnh lên',
  validate_add_product_price: 'Giá bán phải thấp hơn giá gốc trong trường hợp sản phẩm đang giảm giá',
  validate_add_product_quantity: 'Số lượng tối thiểu phải nhỏ hơn số lượng tối đa',
  validate_add_product_id: 'Mã sản phẩm đã tồn tại',
  validate_value_percentage: 'Giá trị giảm giá phải nằm trong khoảng 0 - 100',
  validate_title: 'Vui lòng nhập tên Mã sản phẩm',
  validate_code: 'Vui lòng nhập Mã sản phẩm',
  validate_coupon_value: 'Vui lòng nhập giá trị Giảm giá của mã',
  validate_quantity: 'Vui lòng nhập số lượng Mã giảm giá',
  validate_membership: 'Vui lòng chọn điểm thành viên',
  validate_min_order: 'Vui lòng nhập đơn hàng tối thiểu',
  validate_max_discount: 'Vui lòng nhập giá trị giảm giá tối đa',
  validate_valid_from: 'Vui lòng chọn ngày bắt đầu',
  validate_valid_to: 'Vui lòng chọn ngày kết thúc',
  validate_coupon_code_exist: 'Mã giảm giá đã tồn tại',
  validate_valid_from_greater_than_valid_to: 'Ngày bắt đầu phải nhỏ hơn ngày kết thúc',
  success_modify: 'Sửa thành công',
  fail_modify: 'Sửa thất bại',
  success_delete: 'Xóa thành công',
  fail_delete: 'Xóa thất bại',
  success_add: 'Thêm thành công',
  fail_add: 'Thêm thất bại',
  success_added_to_cart: 'Đã thêm vào giỏ hàng',
  fail_added_to_cart: 'Thêm vào giỏ hàng thất bại',
  success_update_status: 'Cập nhật trạng thái thành công',
  status_repeat: 'Trạng thái đã tồn tại',
  selected: 'Đã chọn',
  validate_fill_product: 'Vui lòng chọn sản phẩm',
  fail_login: 'Đăng nhập thất bại',
  fail_login_message: "Tên đăng nhập hoặc mật khẩu chưa đúng!",
  success_logout: 'Đăng xuất thành công',
  success_logout_message: 'Hẹn gặp lại bạn!',
  fail_logout: 'Đăng xuất thất bại',
  fail_logout_message: 'Bạn chưa đăng nhập!',
  confirm_cancel: 'Bạn có chắc chắn muốn hủy không?',

  // placeholder
  enter_name: 'Nhập tên',
  enter_id: 'Nhập ID sản phẩm.',
  product_id_syntax: 'Cú pháp: "ID1, ID2, ID3, ..."',
  enter_product_name: "Nhập tên sản phẩm",
  placeholder_add_to_favorite: 'Thích quá rùi nà',
  product_suggestion: 'Gợi ý phối đồ từ The Weekdays',
  product_suggestion_description: 'Nhận ngay những gợi ý phối đồ thời trang sành điệu từ The Weekdays để tạo nên phong cách cá tính và độc đáo.',

  // others
  default: 'Mặc định',
  freeship: 'Miễn phí vận chuyển',
  freeship_condition_description: 'Cho đơn hàng từ 300.000đ',
  checkout_conviniently: 'Thanh toán tiện lợi',
  checkout_conviniently_description: '100% Thanh toán bảo mật',
  support_247: 'Hỗ trợ 24/7',
  support_247_description: 'Chăm sóc tận tình',

  // action
  add_to_cart: 'Thêm vào giỏ hàng',
  add_to_favorite: 'Thêm vào yêu thích',

  // Product list page: /listrow
  label_all_products: 'Tất cả sản phẩm',
  label_productpage_header_description_1: 'Chọn từ nhiều màu sắc và kiểu dáng,',
  label_productpage_header_description_2: 'để tạo nên phong cách riêng của bạn.',
  label_sort_by: 'Sắp xếp theo',
  label_sort_by_price: 'Giá thấp đến cao',
  label_sort_by_price_desc: 'Giá cao đến thấp',
  label_sort_by_rating: 'Đánh giá trung bình',
  label_sort_by_popularity: 'Phổ biến',
  label_sort_by_newness: 'Sản phẩm mới nhất',
  label_sort_by_percent_off: "Giảm giá nhiều nhất",
}
